# Generated by Django 3.2.4 on 2021-06-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('tipoDeDocumento', models.CharField(choices=[('ci', 'Cédula de Identidad'), ('pass', 'Pasaporte'), ('dni', 'Documento Nacional de Identificación (Arg)')], default='ci', max_length=5)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('numeroTelefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('laboratorio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='día vacunación')),
                ('direccionLugar', models.CharField(max_length=200)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.persona')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.vacuna')),
            ],
        ),
    ]
