# Generated by Django 3.2.4 on 2021-06-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.CharField(max_length=50, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numeroTelefono',
            field=models.CharField(max_length=200, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='laboratorio',
            field=models.CharField(max_length=200, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='fecha',
            field=models.DateTimeField(verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema.persona'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema.vacuna'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='direccionLugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema.vacunatorio'),
        ),
    ]
