# Generated by Django 3.2.4 on 2021-06-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20210612_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='direccionLugar',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='vacunatorio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='sistema.vacunatorio'),
            preserve_default=False,
        ),
    ]
